version: '3.5'

services:
  agora-server:
    build:
      target: dev
    ports:
      - 5000:5000
    environment:
      AGORA_PATH: "/home/agora/garden"
      AGORA_NAME: "thisagora"
      AGORA_DESCRIPTION: "An [[agora]] is an open distributed knowledge graph."
      RANK: "agora"
      ENABLE_STATS: "true"
      ENABLE_AUTO_PULL: "true"
      JOURNAL_ENTRIES: 10
    volumes:
      - .:/app
      - ./garden:/home/agora/garden
